name: Quality
on: [push]

jobs:
  black:
    name: Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install black
        run: pip install black

      - name: Run black
        run: black . -l 120 --check

  flake8:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install flake8
        run: pip install flake8 flake8-annotations

      - name: Run flake8
        run: flake8 . --count --statistics --show-source

  mypy:
    name: Type checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install mypy
        run: pip install mypy

      - name: Run mypy
        run: mypy .

  bandit:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install bandit
        run: pip install bandit[toml]

      - name: Run bandit
        run: bandit . -r -c "pyproject.toml"

  isort:
    name: Sorting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install isort
        run: pip install isort

      - name: Run isort
        run: isort . --check
